import {chromium} from '@playwright/test';
import fs from 'node:fs';
import {openWorkspace} from './browser-session.mjs';
const root=new URL('../..',import.meta.url).pathname.replace(/\/$/,'');
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 const accessMode=await openWorkspace(page,root);
 await page.getByRole('heading',{name:/Follow the law/}).waitFor();
 await page.getByText('12 opinions',{exact:true}).waitFor();
 const cap=page.getByRole('checkbox',{name:/Harvard Caselaw Access Project/});
 const courtlistener=page.getByRole('checkbox',{name:/CourtListener/});
 if(!(await cap.isChecked())||!(await courtlistener.isDisabled()))throw Error('Database availability is inaccurate');
 await page.getByLabel('Your research question').fill('How do Twombly and Iqbal describe plausibility?');
 await cap.uncheck();
 if(!(await page.getByRole('button',{name:'Search opinions',exact:true}).isDisabled()))throw Error('Empty database selection can search');
 if(!(await page.getByRole('button',{name:/Ask Lex Raptor/}).isDisabled()))throw Error('Empty database selection can generate');
 await page.reload();
 await cap.waitFor();
 if(await cap.isChecked())throw Error('Database preference did not persist');
 await cap.check();
 await page.getByLabel('Your research question').fill('How do Twombly and Iqbal describe plausibility?');
 const request=page.waitForRequest(r=>r.url().includes('/api/research/search?'));
 await page.getByRole('button',{name:'Search opinions',exact:true}).click();
 if(new URL((await request).url()).searchParams.get('database_ids')!=='cap')throw Error('Database filter was not sent');
 await page.getByText('Databases searched: Harvard Caselaw Access Project',{exact:true}).waitFor();
 await page.getByRole('button',{name:/Ashcroft v. Iqbal/}).waitFor();
 await page.getByRole('button',{name:/Ashcroft v. Iqbal/}).click();
 await page.getByRole('heading',{name:'Opinion reader',exact:true}).waitFor();
 await page.getByText(/CAP record labeled majority/).first().waitFor();
 await page.screenshot({path:root+'/data/lex-raptor-research.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:root+'/data/lex-raptor-mobile.png',fullPage:true});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile horizontal overflow');
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByLabel('Decided after').fill('2020-01-01');
 await page.getByRole('button',{name:'Search opinions',exact:true}).click();
 await page.getByText(/No matching opinions in the imported library/).waitFor();
 if(errors.length)throw Error(errors.join('\n'));
 fs.writeFileSync(root+'/data/research-browser-report.json',JSON.stringify({access_mode:accessMode,account_required:accessMode==='account',owner_logo:true,database_selection:true,empty_selection_blocked:true,unavailable_database_disabled:true,selection_persisted:true,selected_database_sent:true,local_case_search:true,full_opinion_reader:true,embedded_dissent_visible:true,date_filter:true,mobile_no_overflow:true,javascript_errors:errors,paid_calls:0},null,2));
 console.log('Research browser: workspace access, search, opinion reader, dissent label, date filter, mobile layout passed; no JavaScript errors.');
} finally { await browser.close(); }
