'use client';
import {useEffect,useState,FormEvent} from 'react';

type Database={id:string;name:string;description:string;homepage:string;searchable:boolean;status:string;cases:number;oldest:string|null;newest:string|null};
type Hit={database_id:string;database_name:string;id:string;case_id:string;name:string;citation:string;court:string;decision_date:string;source_url:string;source_sha256:string;locator:string;opinion_type:string;text:string};
type Coverage={databases:Database[];cases:number;passages:number;oldest:string|null;newest:string|null;courts:string[];scope:string};
type Runtime={mode:string;model:string;ready:boolean;detail?:string};
type Answer={status:string;propositions:{text:string;citations:{chunk_id:string;quote:string}[]}[];limitations:string[]};
type Result={searched_databases?:{id:string;name:string}[];answer:Answer;sources:Hit[];limitation:string;checks:{valid_citations:number;rejected_propositions:number};trace?:{retrieved_passages:number;selected_passages:number};model:string;inference_mode:string;usage:{duration_ms?:number;input_tokens?:number;output_tokens?:number}};
type Run={id:string;query:string;state:string;error_code:string|null;result:Result|null;cancel_requested?:boolean};
type Case={name:string;citation:string;court:string;decision_date:string;source_url:string;source_sha256:string;passages:{id:string;locator:string;opinion_type:string;text:string}[]};
type Api=<T=unknown>(path:string,options?:RequestInit)=>Promise<T>;

export default function Research({api}:{api:Api}){
 const [coverage,setCoverage]=useState<Coverage|null>(null),[runtime,setRuntime]=useState<Runtime|null>(null);
 const [selectedDatabases,setSelectedDatabases]=useState<string[]>([]),[searchedDatabases,setSearchedDatabases]=useState<Database[]>([]);
 const [query,setQuery]=useState(''),[court,setCourt]=useState(''),[after,setAfter]=useState(''),[before,setBefore]=useState('');
 const [hits,setHits]=useState<Hit[]>([]),[searched,setSearched]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [run,setRun]=useState<Run|null>(null),[history,setHistory]=useState<Run[]>([]),[source,setSource]=useState<Hit|null>(null),[opinion,setOpinion]=useState<Case|null>(null),[quote,setQuote]=useState('');
 async function refreshHistory(){setHistory(await api<Run[]>('/research/runs'));}
 useEffect(()=>{Promise.all([api<Coverage>('/library').then(c=>{setCoverage(c);let ids=c.databases.filter(d=>d.searchable).map(d=>d.id);try{const saved=JSON.parse(localStorage.getItem('lex-raptor-databases')||'null');if(Array.isArray(saved))ids=saved.filter(id=>typeof id==='string'&&c.databases.some(d=>d.id===id&&d.searchable));}catch{}setSelectedDatabases(ids);}),api<Runtime>('/runtime').then(setRuntime),refreshHistory()]).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')api<Runtime>('/runtime').then(setRuntime).catch(()=>{});},15000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!run||!['queued','running'].includes(run.state))return;let active=true;const timer=setInterval(async()=>{try{const next=await api<Run>('/research/runs/'+run.id);if(active){setRun(next);if(!['queued','running'].includes(next.state))await refreshHistory();}}catch(e){if(active)setError((e as Error).message);}},2000);return()=>{active=false;clearInterval(timer);};},[run?.id,run?.state]);
 const working=!!run&&['queued','running'].includes(run.state);
 function toggleDatabase(id:string){const ids=selectedDatabases.includes(id)?selectedDatabases.filter(d=>d!==id):[...selectedDatabases,id];setSelectedDatabases(ids);try{localStorage.setItem('lex-raptor-databases',JSON.stringify(ids));}catch{}}
 async function search(e?:FormEvent){e?.preventDefault();if(!selectedDatabases.length){setError('Select at least one database.');return;}setBusy(true);setError('');try{const params=new URLSearchParams({q:query});if(court)params.set('court',court);if(after)params.set('after',after);if(before)params.set('before',before);for(const id of selectedDatabases)params.append('database_ids',id);const r=await api<{passages:Hit[];searched_databases:Database[]}>('/research/search?'+params);setHits(r.passages);setSearchedDatabases(r.searched_databases);setSearched(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function ask(){if(!selectedDatabases.length){setError('Select at least one database.');return;}setBusy(true);setError('');try{const created=await api<{id:string}>('/research/ask',{method:'POST',body:JSON.stringify({query,database_ids:selectedDatabases,court:court||null,after:after||null,before:before||null,idempotency_key:crypto.randomUUID()})});setRun(await api<Run>('/research/runs/'+created.id));setSource(null);setOpinion(null);await refreshHistory();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function openCase(hit:Hit){setSource(hit);setQuote('');try{setOpinion(await api<Case>('/library/cases/'+hit.case_id));}catch(e){setError((e as Error).message);}}
 function download(){if(!run?.result)return;const blob=new Blob([JSON.stringify(run,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='lex-raptor-research-draft.json';a.click();URL.revokeObjectURL(url);}
 const selectedCatalog=coverage?.databases.filter(d=>selectedDatabases.includes(d.id))||[];
 const cases=[...new Map(hits.map(h=>[h.case_id,h])).values()];
 return <div className="research">
  <div className="page-heading"><div><div className="eyebrow muted">OPEN LAW. INDEPENDENT RESEARCH.</div><h1>Follow the law.<br/><em>See the source.</em></h1><p className="subtle">Search your case-law library. Ask a question. Inspect the authority.</p></div><div className="runtime"><span className={'runtime-dot '+(runtime?.ready?'ready':'')}/><strong>{runtime?.mode==='local'?'Local AI · $0 model fees':'API mode'}</strong><small>{runtime?.model||'Checking model…'}</small><small>{runtime?.ready?'Ready for research':runtime?.detail||'Checking connection…'}</small></div></div>
  <section className="card database-picker" aria-label="Research databases"><div className="section-heading"><h2>Databases to search</h2><span className="badge">{selectedDatabases.length} selected</span></div><p className="subtle">Choose the sources for both search and AI answers. Only imported opinions in selected databases are searched.</p><div className="database-options">{coverage?.databases.map(d=><label key={d.id} className={'database-option'+(!d.searchable?' unavailable':'')}><input type="checkbox" checked={selectedDatabases.includes(d.id)} disabled={!d.searchable||busy||working} onChange={()=>toggleDatabase(d.id)}/><span><strong>{d.name}</strong><small>{d.searchable?`${d.cases} opinions · ${d.oldest?.slice(0,4)}–${d.newest?.slice(0,4)} · Local search`:d.status==='empty'?'No opinions imported':'Not connected'}</small><small>{d.description}</small></span></label>)}</div>{!selectedDatabases.length&&<p className="warning" role="status">Select a database to search or ask a question.</p>}<p className="database-note">Private matter documents stay in Matters and are not included in case-law searches.</p></section>
  <section className="card research-search"><form onSubmit={search}><label htmlFor="research-query">Your research question</label><textarea id="research-query" rows={2} maxLength={1200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="What must a plaintiff plead to survive a motion to dismiss?" required/><div className="research-filters"><label>Court<select value={court} onChange={e=>setCourt(e.target.value)}><option value="">All imported courts</option>{coverage?.courts.map(c=><option key={c}>{c}</option>)}</select></label><label>Decided after<input aria-label="Decided after" type="date" value={after} onChange={e=>setAfter(e.target.value)}/></label><label>Decided before<input aria-label="Decided before" type="date" value={before} onChange={e=>setBefore(e.target.value)}/></label></div><div className="actions"><button type="submit" disabled={busy||!query.trim()||!selectedDatabases.length}>Search opinions</button><button type="button" className="primary" onClick={ask} disabled={busy||working||query.trim().length<5||!runtime?.ready||!selectedDatabases.length}>{working?'Researching…':'Ask Lex Raptor →'}</button><span className="subtle">{runtime?.mode==='local'?'Your question stays on your Lex Raptor server.':'Selected passages and your question are sent to the configured API.'}</span></div></form></section>
  <div className="library-scope"><span className="badge">{coverage?selectedCatalog.reduce((n,d)=>n+d.cases,0):'…'} opinions</span><span>{selectedCatalog.map(d=>d.name).join(', ')||'No database selected'}</span><span>Selected coverage · Subsequent treatment not checked</span></div>
  {!searched&&!run&&<div className="research-examples"><span className="eyebrow muted">START WITH A QUESTION</span>{['What is the Celotex summary judgment burden?','How do Twombly and Iqbal describe plausibility?','What does Daubert say about expert testimony?'].map(q=><button key={q} onClick={()=>setQuery(q)}>{q}<span>↗</span></button>)}</div>}
  {error&&<div className="error banner" role="alert">{error}</div>}
  <div className={'research-grid'+(source||opinion?' with-source':'')}><div>
  {run&&<section className="card research-answer"><div className="section-heading"><h2>Research draft</h2><span className="badge">{run.state}</span></div><p className="research-question">{run.query}</p>{run.result?.searched_databases&&<p className="searched-databases">Databases searched: {run.result.searched_databases.map(d=>d.name).join(", ")}</p>}{working&&<div className="research-progress"><span className="runtime-dot ready"/> Reading the selected passages…<button className="quiet" disabled={run.cancel_requested} onClick={async()=>{try{await api('/jobs/'+run.id+'/cancel',{method:'POST'});setRun({...run,cancel_requested:true});}catch(e){setError((e as Error).message);}}}>{run.cancel_requested?'Cancellation requested':'Cancel'}</button></div>}{run.error_code&&<p className="error">{run.error_code.replaceAll('_',' ')}</p>}{run.result&&<><div className="answer-label">{run.result.answer.status==='insufficient'?'Insufficient support in this library':'SOURCE-LINKED FINDINGS · REVIEW REQUIRED'}</div>{run.result.answer.propositions.map((p,i)=><div className="research-proposition" key={i}><p>{p.text}</p><div className="citation-buttons">{p.citations.map((c,j)=>{const s=run.result!.sources.find(s=>s.id===c.chunk_id);return <button className="source-link" key={j} onClick={()=>{if(s){setSource(s);setQuote(c.quote);setOpinion(null);}}}>↗ {s?.citation||'Source'} · {s?.opinion_type}</button>;})}</div></div>)}{run.result.answer.limitations.map((l,i)=><p className="warning" key={i}>{l}</p>)}<p className="research-disclosure">{run.result.limitation}</p><div className="answer-meta"><span>{run.result.checks.valid_citations} exact quotations · {run.result.trace?.selected_passages??0} selected passages</span><span>{run.result.model}{run.result.usage.duration_ms?' · '+(run.result.usage.duration_ms/1000).toFixed(1)+'s':''}</span></div><button className="quiet" onClick={download}>↓ Download research draft & sources</button></>}</section>}
  {searched&&<section className="search-results"><div className="section-heading"><h2>{cases.length} matching opinions</h2><span className="subtle">Keyword relevance · up to 12 passages</span></div><p className="searched-databases">Databases searched: {searchedDatabases.map(d=>d.name).join(', ')}</p>{!cases.length&&<div className="card small-empty">No matching opinions in the imported library. Try different terms or import more public opinions.</div>}{cases.map(h=><article className="card case-result" key={h.case_id}><div className="case-meta"><span>{h.citation}</span><span>{h.decision_date}</span></div><button className="case-name" onClick={()=>openCase(h)}>{h.name} <span>↗</span></button><p className="subtle">{h.database_name} · {h.court} · {h.opinion_type}</p><p className="case-excerpt">{h.text.length>480?h.text.slice(0,480)+'…':h.text}</p><div className="case-links"><button className="quiet" onClick={()=>openCase(h)}>Read imported opinion</button><a href={h.source_url} target="_blank" rel="noreferrer">Original CAP record ↗</a></div></article>)}</section>}
  </div>{(source||opinion)&&<aside className="card research-source"><div className="section-heading"><h2>{opinion?'Opinion reader':'Source passage'}</h2><button className="quiet" onClick={()=>{setSource(null);setOpinion(null);}}>Close</button></div><h3>{opinion?.name||source?.name}</h3><span className="badge">{opinion?.citation||source?.citation}</span><p className="subtle">{opinion?.decision_date||source?.decision_date}</p>{quote&&<blockquote>{quote}</blockquote>}{opinion?opinion.passages.map(p=><div className="opinion-paragraph" key={p.id}><small>{p.locator}</small><p>{p.text}</p></div>):<><p className="subtle">{source?.database_name} · {source?.locator}</p><pre>{source?.text}</pre>{source&&<button className="quiet" onClick={()=>openCase(source)}>Read entire imported opinion →</button>}</>}<a href={opinion?.source_url||source?.source_url} target="_blank" rel="noreferrer">Harvard Caselaw Access Project ↗</a><div className="hash">SHA-256 {opinion?.source_sha256||source?.source_sha256}</div></aside>}</div>
  {!!history.length&&<section className="research-history"><div className="section-heading"><h2>Recent research</h2><span className="subtle">Saved in your workspace</span></div>{history.map(h=><button key={h.id} onClick={async()=>{try{setRun(await api<Run>('/research/runs/'+h.id));setSource(null);setOpinion(null);}catch(e){setError((e as Error).message);}}}><span>{h.query}</span><span className="badge">{h.state}</span></button>)}</section>}
  <footer className="research-footer"><span>Lex Raptor · AGPL-3.0-only · Local inference has no software or API fee; hardware and electricity are yours.</span><a href="/lex-raptor-source.tar.gz" download>Download source code</a><span>Optional managed API service planned. Billing is not enabled.</span></footer>
 </div>;
}
